default:

  #
  # Basic
  #
  server:
    port: 8010

  #
  # Log
  #
  log:
    level: debug

  #
  # Microservice
  #
  microservice:
    basePath: services
    server:
      name: starter/v1
      dependencies: my/other/service/v1
      registrationNetworkInterfacePriority:
        - en0
        - lo0

  #
  # Zookeeper
  #
  zookeeper:
    connectionString: localhost:2181
    retry:
      wait: 1000
      count: 3
